apiVersion: v1
kind: Secret
metadata:
  name: matecloud-secret
  namespace: matecloud
type: Opaque
stringData:
  MYSQL_USER: matecloud
  MYSQL_PASSWORD: change-me-in-prod
  REDIS_PASSWORD: change-me-in-prod
  RABBITMQ_USER: matecloud
  RABBITMQ_PASS: change-me-in-prod
  NACOS_USERNAME: nacos
  NACOS_PASSWORD: change-me-in-prod
